"""Initial

Revision ID: eacd2e02de64
Revises: 
Create Date: 2021-10-02 18:17:08.113235

"""
from alembic import op
import sqlalchemy as sa

import models

# revision identifiers, used by Alembic.

revision = 'eacd2e02de64'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('coord', models.Point(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('users_coord_index', 'users', ['coord'], unique=False, postgresql_using='gist')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('users_coord_index', table_name='users', postgresql_using='gist')
    op.drop_table('users')
    # ### end Alembic commands ###
